### ISSUE TITLE
About acknowledgements

### ISSUE THREAD

**Issue by yxgeee** [YunpengZhai/MEB-Net#1]
Hi,

Congratulations for this work! I saw that you claimed your code is based on open-reid, however, please properly acknowledge our code (https://github.com/yxgeee/MMT) as the following parts are from our MMT instead of open-reid:

1. 
https://github.com/YunpengZhai/MEB-Net/blob/master/main/source_pretrain.py 
from
https://github.com/yxgeee/MMT/blob/master/examples/source_pretrain.py

2. 
https://github.com/YunpengZhai/MEB-Net/blob/master/main/model_test.py 
from 
https://github.com/yxgeee/MMT/blob/master/examples/test_model.py

3. 
https://github.com/YunpengZhai/MEB-Net/blob/master/mebnet/loss/crossentropy.py 
from 
https://github.com/yxgeee/MMT/blob/master/mmt/loss/crossentropy.py

4. 
https://github.com/YunpengZhai/MEB-Net/blob/master/mebnet/loss/triplet.py 
from 
https://github.com/yxgeee/MMT/blob/master/mmt/loss/triplet.py

5. 
https://github.com/YunpengZhai/MEB-Net/blob/master/mebnet/trainers.py (L1-87) 
from 
https://github.com/yxgeee/MMT/blob/master/mmt/trainers.py (L1-87)

The below are highly related,

1. 
https://github.com/YunpengZhai/MEB-Net/blob/master/mebnet/trainers.py (L88-189)
https://github.com/yxgeee/MMT/blob/master/mmt/trainers.py (L157-247）

2. 
https://github.com/YunpengZhai/MEB-Net/blob/master/main/target_train.py
https://github.com/yxgeee/MMT/blob/master/examples/mmt_train_kmeans.py

Thanks!

**Comment by YunpengZhai** [comment]
Thanks for your reminder, we'll update it later. : ）
